{
 "title": "Pravega Scope Dashboard",
 "tags": [ "pravega" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "scope",
    "query": "SHOW TAG VALUES WITH KEY = \"scope\""
   }
  ]
 },
 "panels": [
  { "title": "Write bytes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total write bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_stream",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "stream" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_segment_write_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "scope", "operator": "=~", "value": "/^$scope$/" }
     ]
    },
    {
     "alias": "Scope total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_segment_write_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "scope", "operator": "=~", "value": "/^$scope$/" }
     ]
    }
   ]
  },
  { "title": "Read bytes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Total read bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_stream",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "stream" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_segment_read_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "scope", "operator": "=~", "value": "/^$scope$/" }
     ]
    },
    {
     "alias": "Scope total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_segment_read_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "scope", "operator": "=~", "value": "/^$scope$/" }
     ]
    }
   ]
  },
  { "title": "Write events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Total write events",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "writes" }
   ],
   "targets": [
    {
     "alias": "$tag_stream",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "stream" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_segment_write_events",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "scope", "operator": "=~", "value": "/^$scope$/" }
     ]
    },
    {
     "alias": "Scope total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pravega_segmentstore_segment_write_events",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "scope", "operator": "=~", "value": "/^$scope$/" }
     ]
    }
   ]
  }
 ]
}