#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: Format and mount disks for RabbitMQ hosts
  hosts: rabbitmq
  connection: ssh
  become: true
  tasks:
    - name: RabbitMQ - Format disks
      filesystem:
        fstype: xfs
        dev: '{{ item }}'
      with_items:
        - '/dev/nvme1n1'
    - name: RabbitMQ - Mount disks
      mount:
        path: "{{ item.path }}"
        src: "{{ item.src }}"
        fstype: xfs
        opts: defaults,noatime,nodiscard
        state: mounted
      with_items:
        - { path: "/mnt/data", src: "/dev/nvme1n1" }
    - name: RabbitMQ - Set filesystem permissions
      file:
        path: "/mnt/data"
        state: touch
        mode: "0777"

- name: Install RabbitMQ Cluster
  hosts: rabbitmq
  connection: ssh
  tasks:
  - name: RabbitMQ - Set software versions
    set_fact:
      erlangVersion: 24.3.4.5
      rabbitMqVersion: 3.10.7
  - name: RabbitMQ - Install RPM packages
    yum: pkg={{ item }} state=latest
    with_items:
      - wget
      - sysstat
      - vim
      - socat
  - name: RabbitMQ - Install Erlang
    yum:
      name: https://github.com/rabbitmq/erlang-rpm/releases/download/v{{ erlangVersion }}/erlang-{{ erlangVersion }}-1.el8.x86_64.rpm
      state: present
      disable_gpg_check: yes
  - name: RabbitMQ - Install RabbitMQ Server
    yum:
      name: https://github.com/rabbitmq/rabbitmq-server/releases/download/v{{ rabbitMqVersion }}/rabbitmq-server-{{ rabbitMqVersion }}-1.el8.noarch.rpm
      state: present
      disable_gpg_check: yes

  - name: RabbitMQ - Create rabbitmq.conf file
    template:
      src: "templates/rabbitmq.conf"
      dest: "/etc/rabbitmq/rabbitmq.conf"

  - name: RabbitMQ - Create rabbitmq-env.conf file
    template:
      src: "templates/rabbitmq-env.conf"
      dest: "/etc/rabbitmq/rabbitmq-env.conf"

  - name: RabbitMQ - Start standalone
    systemd:
      state: started
      daemon_reload: yes
      name: "rabbitmq-server"

  - name: RabbitMQ - Install web management plugin
    shell: rabbitmq-plugins enable rabbitmq_management
  - systemd:
      state: restarted
      daemon_reload: yes
      name: "rabbitmq-server"
  - name: RabbitMQ - Restart standalone
    systemd:
      state: restarted
      daemon_reload: yes
      name: "rabbitmq-server"

  - name: RabbitMQ - Clear Erlang cookie
    file:
      path: /var/lib/rabbitmq/.erlang.cookie
      state: absent
  - name: RabbitMQ - Copy Erlang cookie
    copy: src=erlang.cookie  dest=/var/lib/rabbitmq/.erlang.cookie  owner=rabbitmq group=rabbitmq mode=0400
  - name: RabbitMQ - Restart standalone
    systemd:
      state: restarted
      daemon_reload: yes
      name: "rabbitmq-server"
    tags: [restart-rabbitmq]

  - name: RabbitMQ - Check cluster status
    shell: rabbitmqctl cluster_status
    register: result
  - debug:
      msg: '{{ result.stdout }}'

  - name: RabbitMQ - Stop cluster followers
    shell: rabbitmqctl stop_app
    when: inventory_hostname != hostvars[groups['rabbitmq'][0]].inventory_hostname

  - name: RabbitMQ - Join followers to leader
    shell: rabbitmqctl join_cluster rabbit@{{ hostvars[groups['rabbitmq'][0]].private_ip }}
    when: inventory_hostname != hostvars[groups['rabbitmq'][0]].inventory_hostname

  - name: RabbitMQ - Set cluster name
    shell: rabbitmqctl set_cluster_name benchmark_rabbitmq
    when: inventory_hostname == hostvars[groups['rabbitmq'][0]].inventory_hostname

  - name: RabbitMQ - Start cluster followers
    shell: rabbitmqctl start_app
    when: inventory_hostname != hostvars[groups['rabbitmq'][0]].inventory_hostname

  - name: RabbitMQ - Show cluster status
    shell: rabbitmqctl cluster_status
    register: result
  - debug:
      msg: '{{ result.stdout }}'

  - name: RabbitMQ - Create admin/admin profile
    shell:  rabbitmqctl add_user admin  admin
    when: inventory_hostname == hostvars[groups['rabbitmq'][0]].inventory_hostname

  - name: RabbitMQ - Set admin tag
    shell: rabbitmqctl set_user_tags admin administrator
    when: inventory_hostname == hostvars[groups['rabbitmq'][0]].inventory_hostname

  - name: RabbitMQ - Set admin permission
    shell: rabbitmqctl set_permissions -p "/" admin ".*" ".*" ".*"
    when: inventory_hostname == hostvars[groups['rabbitmq'][0]].inventory_hostname

  - name: RabbitMQ - Create high availability policy
    shell: rabbitmqctl set_policy ha-all "^" '{"ha-mode":"exactly","ha-params":2,"ha-sync-mode":"automatic"}'
    when: inventory_hostname == hostvars[groups['rabbitmq'][0]].inventory_hostname

- name: Chrony setup
  hosts: client
  connection: ssh
  become: true
  tasks:
    - name: Chrony - Configure
      template:
        src: "templates/chrony.conf"
        dest: "/etc/chrony.conf"
    - name: Chrony - Restart
      systemd:
        state: restarted
        daemon_reload: yes
        name: "chronyd"

- name: RabbitMQ benchmarking client setup
  hosts: client
  connection: ssh
  become: true
  tasks:
    - name:  Benchmark - Tune kernel
      shell: tuned-adm profile latency-performance
    - name: Benchmark - Install RPM packages
      yum: pkg={{ item }} state=latest
      with_items:
        - wget
        - java-11-openjdk
        - java-11-openjdk-devel
        - sysstat
        - vim
    - name: Benchmark - Clean folder
      file: path=/opt/benchmark state=absent
      tags: [client-code]
    - name: Benchmark - Copy and unpack
      unarchive:
        src: ../../package/target/openmessaging-benchmark-0.0.1-SNAPSHOT-bin.tar.gz
        dest: /opt
      tags: [client-code]
    - name: Benchmark - Install binary
      shell: mv /opt/openmessaging-benchmark-0.0.1-SNAPSHOT /opt/benchmark
      tags: [client-code]
    - name: Benchmark - Configure worker
      template:
        src: "templates/workers.yaml"
        dest: "/opt/benchmark/workers.yaml"
      tags: [client-code]
    - name: Benchmark - Configure classic driver
      template:
        src: "templates/rabbitmq-classic.yaml"
        dest: "/opt/benchmark/driver-rabbitmq/rabbitmq-classic.yaml"
      tags: [client-code]
    - name: Benchmark - Configure quorum driver
      template:
        src: "templates/rabbitmq-quorum.yaml"
        dest: "/opt/benchmark/driver-rabbitmq/rabbitmq-quorum.yaml"
      tags: [client-code]
    - name: Benchmark - Configure experiment driver
      template:
        src: "templates/rabbitmq-experiment.yaml"
        dest: "/opt/benchmark/driver-rabbitmq/rabbitmq-experiment.yaml"
      tags: [client-code]
    - name: Benchmark - Configure worker JVM memory
      lineinfile:
        dest: /opt/benchmark/bin/benchmark-worker
        regexp: '^JVM_MEM='
        line: 'JVM_MEM="-Xms26G -Xmx26G -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -XX:+ParallelRefProcEnabled -XX:+AggressiveOpts -XX:+DoEscapeAnalysis -XX:ParallelGCThreads=6 -XX:ConcGCThreads=6 -XX:+DisableExplicitGC -XX:-ResizePLAB"'
      tags: [client-code]
    - name: Benchmark - Configure client JVM memory
      lineinfile:
        dest: /opt/benchmark/bin/benchmark
        regexp: '^JVM_MEM='
        line: 'JVM_MEM="-Xmx4G"'
      tags: [client-code]
    - name: Benchmark - Install systemd service
      template:
        src: "templates/benchmark-worker.service"
        dest: "/etc/systemd/system/benchmark-worker.service"
      tags: [client-code]
    - name: Benchmark - Start worker
      systemd:
        state: restarted
        daemon_reload: yes
        name: "benchmark-worker"
      tags: [client-code]
